baseURL = "http://yk-Du.github.io/"
languageCode = "en-us"
title = "ykdu's blog"
theme = "hugo-nuo"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[params]
  author = "Yukun Du"
  # bg = "images/grey-prism.svg"
  avatar = "images/stark.jpg"
  seotitle = "ykdu's blog"
  subtitle = "~ Keep Going ~"
  description = ""
  paginate = 10

  # Choose your social networks
  email = "ykdu91@gmail.com"
  github = "yk-Du"
